// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravailPratique2.Models;

#nullable disable

namespace TravailPratique2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502185905_ajouttable")]
    partial class ajouttable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravailPratique2.Models.Devis", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estvalidee")
                        .HasColumnType("bit");

                    b.Property<string>("reparation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeIntervention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("TravailPratique2.Models.Facture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("coutMain")
                        .HasColumnType("float");

                    b.Property<string>("modePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("montantTotal")
                        .HasColumnType("float");

                    b.Property<int>("reparationAssocieeid")
                        .HasColumnType("int");

                    b.Property<bool>("statut")
                        .HasColumnType("bit");

                    b.Property<double>("totalpieces")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("reparationAssocieeid");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("TravailPratique2.Models.Piece", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nom_de_piece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix_approx")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("TravailPratique2.Models.Reparation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("cout")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reparation_associee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Reparations");
                });

            modelBuilder.Entity("TravailPratique2.Models.Utilisateur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("TravailPratique2.Models.Voiture", b =>
                {
                    b.Property<string>("vin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("annee")
                        .HasColumnType("int");

                    b.Property<string>("assurance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAchat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("derniereRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("etatGeneral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("garantitRestant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("kilometrage")
                        .HasColumnType("float");

                    b.Property<string>("marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prixAproximatif")
                        .HasColumnType("int");

                    b.Property<string>("proprietaireActuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeCarburant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vin");

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("TravailPratique2.Models.Facture", b =>
                {
                    b.HasOne("TravailPratique2.Models.Reparation", "reparationAssociee")
                        .WithMany()
                        .HasForeignKey("reparationAssocieeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("reparationAssociee");
                });
#pragma warning restore 612, 618
        }
    }
}
